FROM ubuntu:14:04

MAINTAINER Pål Orby <orby@sendregning.no>

# your global Ubuntu config goes here... Like timezone, locale, apt-get stuff, etc... No application config in here

# Define default command.
CMD ["/bin/bash"]
