FROM company/mysql:5.5

MAINTAINER Pål Orby <orby@sendregning.no>

# Configure MySQL for your application here

#ADD image/startMySQL.sh /startMySQL.sh

# Define default command.
CMD ["/startMySQL.sh"]
