FROM company/apache22-php:5

MAINTAINER Pål Orby <orby@sendregning.no>

# Install Wordpress in Apache and do global WordPress config here, no application config here

# Define default command.
CMD ["/bin/bash"]
