FROM debian:wheezy

MAINTAINER Pål Orby <orby@sendregning.no>

# your global debian config goes here... Like timezone, locale, apt-get stuff, etc... No application config in here

# Define default command.
CMD ["/bin/bash"]
