FROM company/java7-tomcat:7.0.59

MAINTAINER Pål Orby <orby@sendregning.no>

# Configure Tomcat for your application here.

#ADD https://my-ci-server/app1.war /opt/tomcat/webapps

#ADD image/startTomcat.sh /startTomcat.sh

# Define default command.
CMD ["/startTomcat.sh"]
