FROM company/apache22-php5-wordpress:latest

MAINTAINER Pål Orby <orby@sendregning.no>

# Configure WordPress for your application here

#ADD image/startApache.sh /startApache.sh

# Define default command.
CMD ["/startApache.sh"]
